name: C/C++ CI
permissions:
  contents: write

on:
  push:
    branches: [master]
    paths-ignore:
      - '**.md'
      - '.github/**'

  pull_request:
    types: [opened, reopened, synchronize]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  windows:
    name: 'Windows'
    runs-on: windows-2025

    env:
      solution: 'msvc/ReHLDS.sln'
      buildPlatform: 'Win32'
      buildRelease: 'Release'

    steps:
      - name: Configure
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Select PlatformToolset
        id: select_toolset
        shell: pwsh
        run: |
          $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
          $vs2019 = & $vswhere -products * -version "[16.0,17.0)" -property installationPath -latest
          $vs2022 = & $vswhere -products * -version "[17.0,)" -property installationPath -latest
          
          if ($vs2019) {
            "toolset=v140_xp" >> $env:GITHUB_OUTPUT
            Write-Host "Selected v140_xp toolset"
          } elseif ($vs2022) {
            "toolset=v143" >> $env:GITHUB_OUTPUT
            Write-Host "Selected v143 toolset"
          } else {
            Write-Error "No suitable Visual Studio installation found"
            exit 1
          }

      - name: Build
        shell: pwsh
        run: |
          $toolset = '${{ steps.select_toolset.outputs.toolset }}'
          msbuild ${{ env.solution }} -p:Configuration="${{ env.buildRelease }}" /t:Clean,Build /p:Platform=${{ env.buildPlatform }} /p:PlatformToolset=$toolset /p:XPDeprecationWarning=false

      - name: Move files
        run: |
          mkdir publish\debug
          mkdir publish\bin\win32\valve\dlls
          
          move msvc\${{ env.buildRelease }}\hlds.exe publish\bin\win32\hlds.exe
          move msvc\${{ env.buildRelease }}\swds.dll publish\bin\win32\swds.dll
          move msvc\${{ env.buildRelease }}\hlds.pdb publish\debug\hlds.pdb
          move msvc\${{ env.buildRelease }}\swds.pdb publish\debug\swds.pdb

      - name: Deploy artifacts
        uses: actions/upload-artifact@v4
        with:
          name: win32
          path: publish/*

  publish:
    name: 'Publish'
    runs-on: ubuntu-24.04
    needs: [windows]

    steps:
      - name: Deploying windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: win32

      - name: Release artifacts
        uses: softprops/action-gh-release@v2
        id: publish-job
        if: |
          startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            bin/win32/*
            debug/*
            rehlds/lib/steam_api.dll

        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN }}
